version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

  web:
    build: .
    command: gunicorn djangoProject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

    logging:
      driver: "local"
      options:
        mode: "non-blocking"
        max-buffer-size: "4m"
        max-size: "50m"
        max-file: "10"
    depends_on:
      - web
    container_name: nginx_container

  migrations:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    depends_on:
      - db


volumes:
  postgres_data:
  static_volume: